name: Deploy Suite (GitHub Pages)
on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - '.github/workflows/deploy-pages.yml'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Upload the entire /apps folder so landing + each app are available
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
