name: Deploy Suite (GitHub Pages)

on:
  push:
    branches: ["main"]
    # Optional: limit to app changes
    # paths:
    #   - 'apps/**'
    #   - '.github/workflows/deploy-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      # Upload the static site (we publish /apps as the site root)
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps

      # Deploy to Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
